version: '2.4'

services:

  postgresql:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.10-rc-management-alpine
    ports:
      # AMQP protocol port
      - "5672:5672"
      # HTTP management UI
      - "15672:15672"
  users:
    build:
      context: ./user-services
      args:
        - NODE_ENV=development
      target: dev
    ports:
      - "3001:3001"
    volumes:
      - ./user-services:/app/
    environment:
      - SERVICE=user-services
    env_file:
      - ./user-services/.env
    depends_on:
      - postgresql
      - rabbitmq