version: '2.4'

services:

  postgresql:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.10-rc-management-alpine
    ports:
      # AMQP protocol port
      - "5672:5672"
      # HTTP management UI
      - "15672:15672"
